sudo: required

language: sh

services:
  - docker

before_install:
  - docker pull badouralix/zunit

before_script:
  - docker run -t --rm badouralix/zunit zsh --version
  - docker run -t --rm badouralix/zunit --version
  - ls -a

script:
  - docker run -t -v $PWD:/app:ro badouralix/zunit --fail-fast test

after_success:
  # Notify Docker Hub to make a new build
  # See https://stackoverflow.com/questions/34710513/how-can-i-update-full-description-on-docker-hub-automatically
  - >
      [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]
      && curl -XPOST -H "Content-Type: application/json" --data '{"docker_tag_name": "latest"}' --silent --output /dev/null
      https://hub.docker.com/api/build/v1/source/$DOCKERHUB_SOURCE/trigger/$DOCKERHUB_TRIGGER/call/

# vim: ts=2 sw=2 sts=2 et
